// <auto-generated />
using System;
using LogoVisualizer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LogoVisualizer.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260416104930_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LogoVisualizer.Data.Models.PrintTechnique", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PrintTechniques");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Silkscreen/serigrafi-tryk",
                            Name = "Screen Print"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Broderi",
                            Name = "Embroidery"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Sublimationstryk (kræver lyst syntetisk stof)",
                            Name = "Sublimation"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Laser- eller mekanisk gravering",
                            Name = "Engraving"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Direct-to-garment tryk",
                            Name = "DTG"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Tampontryk — velegnet til små flader",
                            Name = "Pad Print"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Digitalt tryk / inkjet",
                            Name = "Digital Print"
                        });
                });

            modelBuilder.Entity("LogoVisualizer.Data.Models.PrintZone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<int?>("MaxColors")
                        .HasColumnType("int");

                    b.Property<decimal>("MaxPhysicalHeightMm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MaxPhysicalWidthMm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.Property<int>("X")
                        .HasColumnType("int");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("PrintZones");
                });

            modelBuilder.Entity("LogoVisualizer.Data.Models.PrintZoneTechnique", b =>
                {
                    b.Property<int>("PrintZoneId")
                        .HasColumnType("int");

                    b.Property<int>("PrintTechniqueId")
                        .HasColumnType("int");

                    b.HasKey("PrintZoneId", "PrintTechniqueId");

                    b.HasIndex("PrintTechniqueId");

                    b.ToTable("PrintZoneTechniques");
                });

            modelBuilder.Entity("LogoVisualizer.Data.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ImageHeight")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ImageWidth")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("LogoVisualizer.Data.Models.PrintZone", b =>
                {
                    b.HasOne("LogoVisualizer.Data.Models.Product", "Product")
                        .WithMany("PrintZones")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("LogoVisualizer.Data.Models.PrintZoneTechnique", b =>
                {
                    b.HasOne("LogoVisualizer.Data.Models.PrintTechnique", "PrintTechnique")
                        .WithMany("PrintZoneTechniques")
                        .HasForeignKey("PrintTechniqueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LogoVisualizer.Data.Models.PrintZone", "PrintZone")
                        .WithMany("AllowedTechniques")
                        .HasForeignKey("PrintZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrintTechnique");

                    b.Navigation("PrintZone");
                });

            modelBuilder.Entity("LogoVisualizer.Data.Models.PrintTechnique", b =>
                {
                    b.Navigation("PrintZoneTechniques");
                });

            modelBuilder.Entity("LogoVisualizer.Data.Models.PrintZone", b =>
                {
                    b.Navigation("AllowedTechniques");
                });

            modelBuilder.Entity("LogoVisualizer.Data.Models.Product", b =>
                {
                    b.Navigation("PrintZones");
                });
#pragma warning restore 612, 618
        }
    }
}
